name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # หรือ branch ที่คุณใช้ deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: [18.x, 20.x, 22.x]  # หรือเวอร์ชันที่คุณใช้

      - name: Install Dependencies
        run: npm install

      - name: Remove old build folder
        run: rm -rf build  # ลบโฟลเดอร์ build

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
